version: '3.9'

services:
  web:
    build: .
    container_name: technews_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/technews
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  celery_worker:
    build: .
    container_name: technews_celery 
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/technews
    env_file:
      - .env
    depends_on: 
      - web
      - redis
    
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    env_file:
      - .env
