version: '3.9'

services:
  web:
    build: .
    container_name: technews_web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
    volumes:
      - .:/technews
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 0.0.0.0 [::1] rozhinpanav.pythonanywhere.com
      - CELERY_BROKER=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    container_name: technews_redis
    ports:
      - "6379:6379"
    env_file:
      - .env

  celery_worker:
    build: .
    container_name: technews_celery_worker
    command: celery -A core worker --loglevel=info -E
    volumes:
      - .:/technews
    env_file:
      - .env
    depends_on: 
      - web
      - redis
    restart: always

  celery_beat:
    build: .
    container_name: technews_celery_beat
    command: celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler

    volumes:
      - .:/technews
    env_file:
      - .env
    depends_on:
      - redis
      - web
    restart: always
  
  flower:
    build: .
    container_name: technews_celery_flower
    command: celery -A core flower --basic_auth=admin:password123
    ports:
      - "5555:5555"
    volumes:
      - .:/technews
    working_dir: /technews
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
