version: '3.9'

services:
  web:
    build: .
    container_name: technews_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/technews
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    env_file:
      - .env

  celery_worker:
    build: .
    container_name: technews_celery_worker
    command: celery -A core worker --loglevel=info -E
    volumes:
      - .:/technews
    env_file:
      - .env
    depends_on: 
      - web
      - redis

  celery_beat:
    build: .
    container_name: technews_celery_beat
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/technews
    env_file:
      - .env
    depends_on:
      - redis
      - web
  
  flower:
    build: .
    container_name: technews_celery_flower
    command: celery -A core flower --basic_auth=admin:password123
    ports:
      - "5555:5555"
    volumes:
      - .:/technews
    working_dir: /technews
    env_file:
      - .env
    depends_on:
      - redis
