# Generated by Django 5.2.4 on 2025-07-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
