# Generated by Django 4.2.11 on 2025-07-25 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsimage_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(help_text='Full text content of the news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Datetime when the news was published', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for the article', unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(help_text='Origin or publisher of the news', max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(help_text='List of tags associated with the news', related_name='news_items', to='news.tag'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='The title of the news article', max_length=255),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative descriptive text for the image', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Uploaded image file (if available locally)', null=True, upload_to='news/images/'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Remote URL for the image (if scraped or external)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Indicates if this is the primary image for the news'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(help_text='The news item this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='position',
            field=models.PositiveIntegerField(blank=True, help_text='Ordering index for multiple images of a news item', null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='The name of the tag (must be unique)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the tag name (auto-generated if left blank)', max_length=120, unique=True),
        ),
    ]
