# Generated by Django 5.2.4 on 2025-07-19 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0003_alter_newsimage_alt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(unique=True)),
                ('mapped_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.news')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
